### ISSUE TITLE
Could not fetch configs from config-service

### ISSUE THREAD

**Issue by oognuyh** [oognuyh/msa-chat#20]
```
INFO 5 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://config-service:8083
WARN 5 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://config-service:8083/discovery-service/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
```

**Comment by oognuyh** [comment]
:information_source: Add wait-for-it.sh and override entrypoint in docker-compose.yml as follows:
```
  discovery-service:
    image: oognuyh/msa-chat-discovery-service
    container_name: discovery-service
    depends_on:
      - config-service
    ports:
      - "8081:8081"
    volumes: 
      - ./scripts/wait-for-it.sh:/wait.sh
    entrypoint: sh -c "/wait.sh config-service:8083 -t 120 && java -Xmx200m -jar service.jar"
    networks:
      - cloud-network
```
